version: '3'
services:

  ### PHP FPM Service #################################
  app:
    build:
      context: .docker
      args:
        BUILD_OPCACHE: "false"
    restart: unless-stopped
    tty: true    
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - mysql

  ### Web server ###################################
  web:
    image: nginx:${NGINX_VERSION:-latest}
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

### Database #########################################
  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    volumes:
      - .docker/mysql/vol/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-l8}
    restart: unless-stopped
    ports:
      - "3307:3306"
    networks:
      - app-network

### Database Two #######################################
  mysql_published:
    image: mariadb:${MARIADB_VERSION:-latest}
    volumes:
      - .docker/mysql2/vol/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-published}
    restart: unless-stopped
    ports:
      - "3308:3306"
    networks:
      - app-network

### Redis ################################################
  redis:
    image: redis:${REDIS_VERSION:-latest}
    volumes:
      - .docker/redis/vol:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network

### Docker Networks ####################################
networks:
  app-network:
    driver: bridge
