version: '3'
services:

  #PHP Service
  app:
    build:
      context: .docker
      args:
        BUILD_OPCACHE: "false"
    restart: unless-stopped
    tty: true    
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  # Web server
  web:
    image: nginx:mainline
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
